### ISSUE TITLE
Add a changelog to the automatically published releases

### ISSUE THREAD

**Issue by rdw-software** [RevivalEngine/WebClient#48]
Goals:

- [ ] The changelog should be taken from an existing file, ``CHANGES.MD``
- [ ] How this file is created/edited is not a concern for this issue (but it will likely be auto-generated)
- [ ] This file must have been updated since the last release, or the action will fail
- [ ] Failure of this workflow should block the release itself

We can use this as a template:

````
name: Changelog Enforcer
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dangoslen/changelog-enforcer@v2
        with:
          changeLogPath: 'CHANGELOG.md'
          skipLabels: 'skip changelog'
          missingUpdateErrorMessage: >
            No update to CHANGELOG.md found! Please add a changelog entry to it
            describing your change with a link to the issue or pull request.
            Please note that the keepachangelog (https://keepachangelog.com)
            format is used. If your change is not applicable for a changelog
            entry, add a 'skip changelog' label to the pull request to skip
            the changelog enforcer.
````
